baseURL = "https://davorbadrov.github.io/"
languageCode = "en-us"
title = "Davor Badrov"
author = "Davor Badrov"
theme = "cocoa-eh"

[params]
  subtitle = "My personal website"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateform = "Jan 2, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 MST"
  description = "Davor Badrov's personal site"
  copyright = "Copyright © 2017 Davor Badrov"
#  logofile = "img/logo.png"
  faviconfile = "img/logo.png"
  highlightjs = true
  progressively = true
  latestpostcount = 5
  lang = "en"
  github = "davorbadrov"
  email = "dev.davor.badrov@gmail.com"
  linkedin = "davor-badrov-670b0312b"
  posts_navigation = false
  extracssfiles = ["css/custom.css"]

[permalinks]
  blog = "blog/:slug/"


[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
